apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: shadowsocks
    app: shadowsocks
  name: shadowsocks
spec:
  type: NodePort
  ports:
    - name: shadowsocks-tcp
      # TODO: $(SHADOWSOCKS_PORT) is rendered as string
      # port: $(SHADOWSOCKS_PORT)
      port: 8234
      protocol: TCP
    - name: shadowsocks-udp
      # TODO: $(SHADOWSOCKS_PORT) is rendered as string
      # port: $(SHADOWSOCKS_PORT)
      port: 8234
      protocol: UDP
  selector:
    app.kubernetes.io/name: shadowsocks
