image: "contrun/gitpod-nix"

tasks:
  - name: tailscaled
    command: |
      if [ -n "${TAILSCALE_STATE_MYPROJECT}" ]; then
        # restore the tailscale state from gitpod user's env vars
        sudo mkdir -p /var/lib/tailscale
        echo "${TAILSCALE_STATE_MYPROJECT}" | sudo tee /var/lib/tailscale/tailscaled.state > /dev/null
      fi
      sudo tailscaled
  - name: tailscale
    command: |
      if [ -n "${TAILSCALE_STATE_MYPROJECT}" ]; then
        sudo -E tailscale up
      else
        sudo -E tailscale up --hostname "gitpod-${GITPOD_GIT_USER_NAME// /-}-$(echo ${GITPOD_WORKSPACE_CONTEXT} | jq -r .repository.name)"
        # store the tailscale state into gitpod user
        gp env TAILSCALE_STATE_MYPROJECT="$(sudo cat /var/lib/tailscale/tailscaled.state)"
      fi

vscode:
  extensions:
    - eamodio.gitlens
    - mkhl.direnv
    - bbenoist.Nix
    - jnoortheen.nix-ide
    - kamadorueda.alejandra
    - rust-lang.rust-analyzer
    - PKief.material-icon-theme
    - tamasfe.even-better-toml
    - evilz.vscode-reveal
    - vscode-org-mode.org-mode
