repos:
- repo: https://github.com/nix-community/nixpkgs-fmt
  rev: v1.2.0
  hooks:
    - id: nixpkgs-fmt
      description: Format nix code with nixpkgs-fmt.
      files: \.nix$
      always_run: true
