repos:
  - repo: https://github.com/nix-community/nixpkgs-fmt
    rev: v1.2.0
    hooks:
      - id: nixpkgs-fmt
        description: Format nix code with nixpkgs-fmt.
        types: [file, nix]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.1
    hooks:
      - id: prettier
        exclude: sops/secrets.yaml
