- hosts: "{{ host | default('localhost') }}"
  gather_facts: "{{ gather_facts | default('no') }}"
  tasks:
    - name: Get roles
      set_fact:
        role_list: "{{ roles.split(',') }}"

    - name: Set up environment variables
      include_tasks: ./dotenv.yaml
      vars:
        folder: "{{ item }}"
      loop:
        "{{ role_list }}"

    - name: Run jupyter hub
      shell:
        cmd: |
          dhall-to-yaml < generate.dhall > generated.yaml
          helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
          helm repo update
          helm upgrade --timeout 36000s --install jupyterhub jupyterhub/jupyterhub --version=0.9.1 --values generated.yaml
        chdir: "jupyterhub"
      environment: "{{ env_vars }}"
      when: "'jupyterhub' in role_list"
