---
roles:
  - name: artis3n.tailscale
  - name: fabiocruzcoelho.envoyproxy
  - src: https://github.com/nginxinc/ansible-role-nginx-config.git
    version: 1e3a22886dffa449c8a60b3b734bfaa975dab551
    name: nginxinc.nginx_config

collections:
  - name: community.general
  - name: community.kubernetes
  - name: nginxinc.nginx_core
