---
roles:
  - name: aisbergg.systemd-resolved
    src: https://github.com/aisbergg/ansible-role-systemd-resolved
    version: da90c892350c0e77db0ee511f591678ec89c051a
  - name: artis3n.tailscale
  - name: hugoprudente.envoyproxy
  - name: patrickjahns.promtail
  - name: ajaykumar4.zerotier
    src: https://github.com/ajaykumar4/ansible-role-zerotier.git
  - name: nginxinc.nginx_config
    src: https://github.com/nginxinc/ansible-role-nginx-config.git
    version: 1e3a22886dffa449c8a60b3b734bfaa975dab551

collections:
  - name: community.general
  - name: community.kubernetes
  - name: nginxinc.nginx_core
