---
roles:
  - name: ho-ansible.systemd-resolved
    src: https://github.com/ho-ansible/systemd-resolved.git
    version: 522d772f84dabbd203c5a1909757ee76cc22c173
  - name: artis3n.tailscale
  - name: hugoprudente.envoyproxy
  - name: ajaykumar4.zerotier
    src: https://github.com/ajaykumar4/ansible-role-zerotier.git
  - name: nginxinc.nginx_config
    src: https://github.com/nginxinc/ansible-role-nginx-config.git
    version: 1e3a22886dffa449c8a60b3b734bfaa975dab551

collections:
  - name: community.general
  - name: community.kubernetes
  - name: nginxinc.nginx_core
