- hosts: localhost
  gather_facts: false
  tasks:
    - assert:
        that:
          - deployments is defined
          - deployments | length > 0
    - set_fact:
        artifacts_dir: "{{ playbook_dir }}/artifacts"

    - name: "Ensures {{ artifacts_dir }} exists"
      file:
        path: "{{ artifacts_dir }}"
        state: directory

- hosts: edge_proxies
  tasks:
    - assert:
        that:
          - groups["backends"] is defined
          - groups["backends"] | length > 0

    - name: Install and configure nginx
      when: '"edge_proxies" in deployments and use_nginx'
      block:
        - name: Install nginx
          include_role:
            name: nginxinc.nginx_core.nginx
          vars:
            nginx_debug_output: true

    - name: Install and configure envoy
      when: '"edge_proxies" in deployments and use_envoy'
      block:
        - name: Install envoy
          include_role:
            name: fabiocruzcoelho.envoyproxy
        - name: Copy templates to default directory
          template:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            mode: "0644"
          loop:
            - src: envoy.yaml.j2
              dest: /etc/envoy/envoy.yaml
          register: envoy_config
        - name: Start/reload Envoy Proxy
          service:
            name: envoyproxy
            state: restarted
            enabled: yes
          when: envoy_config.changed

- hosts: localhost
  gather_facts: false
  tasks:
    - name: Install jupyterhub
      when: '"jupyterhub" in deployments'
      block:
        - name: Decrypt jupyterhub secrets
          template:
            src: files/jupyterhub.yaml.encrypted
            dest:  "{{ artifacts_dir }}/jupyterhub.yaml.decrypted"
            decrypt: true
        - name: Install jupyterhub
          community.kubernetes.helm:
            name: jupyterhub
            kubeconfig: "{{ lookup('env', 'KUBECONFIG') | default(lookup('env', 'K8S_AUTH_KUBECONFIG')) }}"
            atomic: false
            chart_repo_url: "https://jupyterhub.github.io/helm-chart/"
            chart_version: "0.9.1"
            chart_ref: jupyterhub
            release_namespace: default
            create_namespace: true
            values_files:
              - "{{ artifacts_dir }}/jupyterhub.yaml.decrypted"
              - "files/jupyterhub.yaml"
