- hosts: localhost
  gather_facts: false
  tasks:
    - assert:
        that:
          - deployments is defined
          - deployments | length > 0

    - set_fact:
        artifacts_dir: "{{ playbook_dir }}/artifacts"
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') | default(lookup('env', 'K8S_AUTH_KUBECONFIG')) }}"
        default_namespace: "default"

    - name: "Ensures {{ artifacts_dir }} exists"
      file:
        path: "{{ artifacts_dir }}"
        state: directory

- hosts: overlay_nodes
  tasks:
    - name: Install zerotier one
      when:
        - use_zerotier
        - '"overlay_nodes" in deployments'
      become: true
      block:
        - assert:
            that:
              - zerotier_network_id is defined
        - include_role:
            role: ajaykumar4.zerotier

    - name: Install tailscale
      when:
        - use_tailscale
        - '"overlay_nodes" in deployments'
      become: true
      block:
        - set_fact:
            tailscale_up_skip: true
          when: tailscale_auth_key is not defined and tailscale_up_skip is not defined
        - include_role:
            role: artis3n.tailscale

- hosts: edge_proxies
  tasks:
    - set_fact:
        tcp_forwarding_ports: "{{ edge_proxy_tcp_forwarding_ports }}"
        udp_forwarding_ports: "{{ edge_proxy_udp_forwarding_ports }}"
        resolver: "{{ edge_proxy_resolvers }}"
        backend_ips: "{{ edge_proxy_backend_ip_addresses.split(',') }}"
        port_mappings: "{{ edge_proxy_port_mappings }}"

    - name: Install and configure nginx
      when:
        - '"edge_proxies" in deployments'
        - use_nginx
      block:
        - name: Install nginx
          include_role:
            name: nginxinc.nginx_core.nginx
          vars:
            nginx_debug_output: true
            nginx_install_source_pcre: true
            nginx_logrotate_conf_enable: true

        - name: Copy templates to default directory
          template:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            mode: "0644"
          loop:
            - src: nginx.conf.j2
              dest: /etc/nginx/nginx.conf
          register: nginx_config

        - name: Start/reload Nginx Proxy
          service:
            name: nginx
            state: restarted
            enabled: yes
          when: nginx_config.changed

    - name: Install and configure envoy
      when:
        - '"edge_proxies" in deployments'
        - use_envoy
      block:
        - name: Add envoy gpg key
          when: ansible_facts['os_family'] == "Debian"
          ansible.builtin.apt_key:
            url: https://deb.dl.getenvoy.io/public/gpg.8115BA8E629CC074.key
            state: present

        - name: Set envoy ubuntu repo
          when: ansible_facts['distribution'] == "Ubuntu"
          set_fact:
            envoyproxy_repository:
              - "deb [arch=amd64] https://deb.dl.getenvoy.io/public/deb/ubuntu {{ ansible_facts['distribution_release'] }} stable"

        - name: Install envoy
          include_role:
            name: hugoprudente.envoyproxy

        - name: Copy templates to default directory
          template:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            mode: "0644"
          loop:
            - src: envoy.yaml.j2
              dest: /etc/envoy/envoy.yaml
          register: envoy_config

        - name: Start/reload Envoy Proxy
          service:
            name: envoyproxy
            state: restarted
            enabled: yes
            daemon_reload: yes
          when: envoy_config.changed

- hosts: localhost
  gather_facts: false
  tasks:
    - name: Install jupyterhub
      when: '"jupyterhub" in deployments'
      block:
        - name: Decrypt secrets
          template:
            src: "{{ item }}"
            dest:  "{{ artifacts_dir }}"
            decrypt: true
          with_fileglob:
            - "files/jupyterhub.yaml*"
        - name: Install
          community.kubernetes.helm:
            name: jupyterhub
            kubeconfig: "{{ kubeconfig }}"
            atomic: false
            chart_repo_url: "https://jupyterhub.github.io/helm-chart/"
            chart_version: "0.9.1"
            chart_ref: jupyterhub
            release_namespace: "{{ default_namespace }}"
            create_namespace: true
            values_files: "{{ lookup('fileglob', '{{ artifacts_dir }}/jupyterhub.yaml*') }}"

- hosts: localhost
  gather_facts: false
  tasks:
    - name: Install cockroachdb
      when:
        - '"database" in deployments'
        - use_cockroachdb
      block:
        - name: Decrypt secrets
          template:
            src: "{{ item }}"
            dest:  "{{ artifacts_dir }}"
            decrypt: true
          with_fileglob:
            - "files/cockroachdb.yaml*"
        - name: Install
          community.kubernetes.helm:
            name: coachroachdb
            chart_repo_url: "https://charts.cockroachdb.com/"
            chart_version: "5.0.6"
            chart_ref: cockroachdb
            release_namespace: "{{ default_namespace }}"
            kubeconfig: "{{ kubeconfig }}"
            create_namespace: true
            values_files: "{{ lookup('fileglob', '{{ artifacts_dir }}/cockroachdb.yaml*') }}"
