schema = 3

[mod]
  [mod."cloud.google.com/go/iam"]
    version = "v1.1.1"
    hash = "sha256-VANDj1f2Ckjco+l0KG4uboPE5i2xbbclvZGCojqWepc="
  [mod."filippo.io/edwards25519"]
    version = "v1.0.0"
    hash = "sha256-APnPAcmItvtJ5Zsy863lzR2TjEBF9Y66TY1e4M1ap98="
  [mod."github.com/AndreasBriese/bbloom"]
    version = "v0.0.0-20190825152654-46b345b51c96"
    hash = "sha256-ydIJ4QKvQsDSAook9y0doDaTeXpyQUy1T+ySfOgFLAg="
  [mod."github.com/Azure/go-ntlmssp"]
    version = "v0.0.0-20221128193559-754e69321358"
    hash = "sha256-tkVqtJKQZl5WUJSe9FZBCPwuD//WPleYvrQ46rkD4jU="
  [mod."github.com/Masterminds/goutils"]
    version = "v1.1.1"
    hash = "sha256-MEvA5e099GUllILa5EXxa6toQexU1sz6eDZt2tiqpCY="
  [mod."github.com/Masterminds/semver/v3"]
    version = "v3.2.1"
    hash = "sha256-VKHIquwriyOL8A0qgtmap/3cGEOpDokOLtPg1w4xjMA="
  [mod."github.com/Masterminds/sprig/v3"]
    version = "v3.2.3"
    hash = "sha256-1GLZic3WQIBZGyjvyHbfcZ/7EV7oNzNhkwEiiTpVfL4="
  [mod."github.com/Microsoft/go-winio"]
    version = "v0.6.1"
    hash = "sha256-BL0BVaHtmPKQts/711W59AbHXjGKqFS4ZTal0RYnR9I="
  [mod."github.com/antlr/antlr4/runtime/Go/antlr/v4"]
    version = "v4.0.0-20230321174746-8dcc6526cfb1"
    hash = "sha256-kuqZ7vX7JsfGd+VxOK6lb0iVpq62XjKVguTkiPS8QvE="
  [mod."github.com/aryann/difflib"]
    version = "v0.0.0-20210328193216-ff5ff6dc229b"
    hash = "sha256-QaGcdek1bA6eekbxVTDaidFZrWeGk+of35NTV94lVXw="
  [mod."github.com/beevik/etree"]
    version = "v1.1.0"
    hash = "sha256-tvvc/RbFjTppdAKs1xUnMhfTXiW4Yr4CQ9NmrhF8uIk="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/caddyserver/caddy/v2"]
    version = "v2.7.3"
    hash = "sha256-1AYRT/0GWGzD3+NK9yy2DQ8QYibXHYb70sVQBz4+AhE="
  [mod."github.com/caddyserver/certmagic"]
    version = "v0.19.1"
    hash = "sha256-zyIosg9+3hhDt6e1i9p25VnjravvnIzzG6ZAB1X5eZ0="
  [mod."github.com/cespare/xxhash"]
    version = "v1.1.0"
    hash = "sha256-nVDTtXH9PC3yJ0THaQZEN243UP9xgLi/clt5xRqj3+M="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.2.0"
    hash = "sha256-nPufwYQfTkyrEkbBrpqM3C2vnMxfIz6tAaBmiUP7vd4="
  [mod."github.com/chzyer/readline"]
    version = "v1.5.1"
    hash = "sha256-6wKd6/JZ9/O7FwSyNKE3KOt8fVPZEunqbTHQUxlOUNc="
  [mod."github.com/cpuguy83/go-md2man/v2"]
    version = "v2.0.2"
    hash = "sha256-OvWCtDsVrYzM84SMQwOXPLBxnWnMC1hDm+KiI6zm3uk="
  [mod."github.com/crewjam/httperr"]
    version = "v0.2.0"
    hash = "sha256-bDtSUX19gEMm/U92fLAiNZSKWmco9rvl6u8avD5oTyo="
  [mod."github.com/crewjam/saml"]
    version = "v0.4.13"
    hash = "sha256-QXumH1UEDfME2KtN1F+jjl2FKG9OYQ+nShrw5o0UH/U="
  [mod."github.com/dgraph-io/badger"]
    version = "v1.6.2"
    hash = "sha256-D/iXyiNZ8/7tBtA9msk10vVWfohWEPqFdobzRwKlvQQ="
  [mod."github.com/dgraph-io/badger/v2"]
    version = "v2.2007.4"
    hash = "sha256-+KwqZJZpViv8S3TqUVvPXrFoMgWFyS3NoLsi4RR5fGk="
  [mod."github.com/dgraph-io/ristretto"]
    version = "v0.1.1"
    hash = "sha256-Wr9ovXhGi71+n37EnrpIj2o9goyaQHtY4Vvurv6IVlY="
  [mod."github.com/dgryski/go-farm"]
    version = "v0.0.0-20200201041132-a6ae2369ad13"
    hash = "sha256-aOMlPwFY36bLiiIx4HonbCYRAhagk5N6HAWN7Ygif+E="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/emersion/go-sasl"]
    version = "v0.0.0-20220912192320-0145f2c60ead"
    hash = "sha256-xIodEk9px5t6n719uyn4PUrH9eh9QqZDu0Mz/02hcwE="
  [mod."github.com/emersion/go-smtp"]
    version = "v0.16.0"
    hash = "sha256-LAgQf5+KxyzgsiXHDUlBVA5Y470nVWHQqLlSdbY87t0="
  [mod."github.com/go-asn1-ber/asn1-ber"]
    version = "v1.5.4"
    hash = "sha256-9a0DMr92zbvAq5Yi3mUVpWB5yLniLhNqaot4ykC8rD4="
  [mod."github.com/go-kit/kit"]
    version = "v0.12.0"
    hash = "sha256-5RkXo6s0oye8etgD5qy+AvkkkNsQ6jc0kWJj6flA4GM="
  [mod."github.com/go-kit/log"]
    version = "v0.2.1"
    hash = "sha256-puLJ+up45X2j9E3lXvBPKqHPKOA/sFAhfCqGxsITW/Y="
  [mod."github.com/go-ldap/ldap/v3"]
    version = "v3.4.4"
    hash = "sha256-ADnAjlu0Ybxv2bc6LLE1FoRhF5+wWFBWV3EzgqPVwsM="
  [mod."github.com/go-logfmt/logfmt"]
    version = "v0.6.0"
    hash = "sha256-RtIG2qARd5sT10WQ7F3LR8YJhS8exs+KiuUiVf75bWg="
  [mod."github.com/go-sql-driver/mysql"]
    version = "v1.7.1"
    hash = "sha256-3iKt+BKDz5FX2246Tg41weIuEDYd1YI40N6alJI9Bks="
  [mod."github.com/go-task/slim-sprig"]
    version = "v0.0.0-20230315185526-52ccab3ef572"
    hash = "sha256-D6NjCQbcYC53NdwzyAm4i9M1OjTJIVu4EIt3AD/Vxfg="
  [mod."github.com/golang-jwt/jwt/v4"]
    version = "v4.5.0"
    hash = "sha256-dyKL8wQRApkdCkKxJ1knllvixsrBLw+BtRS0SjlN7NQ="
  [mod."github.com/golang/glog"]
    version = "v1.1.1"
    hash = "sha256-lzIGeY7v/vAN1/ym3FHTtMO5lSVeqcFbEcXceu3fz+M="
  [mod."github.com/golang/mock"]
    version = "v1.6.0"
    hash = "sha256-fWdnMQisRbiRzGT3ISrUHovquzLRHWvcv1JEsJFZRno="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/golang/snappy"]
    version = "v0.0.4"
    hash = "sha256-Umx+5xHAQCN/Gi4HbtMhnDCSPFAXSsjVbXd8n5LhjAA="
  [mod."github.com/google/cel-go"]
    version = "v0.17.1"
    hash = "sha256-uyaiYnOYErlzku9qZDgCphcE+QKCpIo1mUjpNRUq26Q="
  [mod."github.com/google/pprof"]
    version = "v0.0.0-20230728192033-2ba5b33183c6"
    hash = "sha256-7pf9mbJkjFf/aA6bBxEHhbjmXYwPggDsDQhQdIjxrc8="
  [mod."github.com/google/uuid"]
    version = "v1.3.0"
    hash = "sha256-QoR55eBtA94T2tBszyxfDtO7/pjZZSGb5vm7U0Xhs0Y="
  [mod."github.com/greenpau/caddy-security"]
    version = "v1.1.19"
    hash = "sha256-4Y+frlV5EHNrpvihKTqIDLpSicG9canrz6nwJz/H248="
  [mod."github.com/greenpau/go-authcrunch"]
    version = "v1.0.40"
    hash = "sha256-WGlIBgU7eX0nNitl8sMiOX7exBWhWAzGqwnQYNPxh+E="
  [mod."github.com/greenpau/versioned"]
    version = "v1.0.28"
    hash = "sha256-q4g3goW2+3JBXvkJRXIv9rfisZsV0CtTVAy8TXZ8nDI="
  [mod."github.com/huandu/xstrings"]
    version = "v1.4.0"
    hash = "sha256-lw0qFsUNW6ZPXNwawpUSfJQjZ+/PKMLkC/yW64t1yng="
  [mod."github.com/imdario/mergo"]
    version = "v0.3.16"
    hash = "sha256-gh2TEAq8YrZOEAf6SFW4AIcEEUguD68G+7/VUnBeWwM="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/jackc/chunkreader/v2"]
    version = "v2.0.1"
    hash = "sha256-LNAEmbsxWOVPtcQ1fE1JC1yTaqyvZGa/k4zocWFBRTo="
  [mod."github.com/jackc/pgconn"]
    version = "v1.14.1"
    hash = "sha256-ELPHPWHea8+/PlTgZjNaQK4iuF7534i7tYmwo5APX9Q="
  [mod."github.com/jackc/pgio"]
    version = "v1.0.0"
    hash = "sha256-4W0PGZlkbBZcSJmPyXi9v1gAJIK9ujVLlcbxEOx9J1A="
  [mod."github.com/jackc/pgpassfile"]
    version = "v1.0.0"
    hash = "sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM="
  [mod."github.com/jackc/pgproto3/v2"]
    version = "v2.3.2"
    hash = "sha256-/5UWuc3rR/aBwcNZ4gDiMoYIrkWs5UQkrfQj2//vmIU="
  [mod."github.com/jackc/pgservicefile"]
    version = "v0.0.0-20221227161230-091c0ba34f0a"
    hash = "sha256-rBtUw15WPPDp2eulHXH5e2zCIed1OPFYwlCpgDOnGRM="
  [mod."github.com/jackc/pgtype"]
    version = "v1.14.0"
    hash = "sha256-vGfWF6+NzFWS6XhFXEjrxxG44/kSSj1fB5j9OuNQlQs="
  [mod."github.com/jackc/pgx/v4"]
    version = "v4.18.1"
    hash = "sha256-ojdH9UlWDEpUOJ7nXLkMqgq7ix0phJegPPJp45LhKFA="
  [mod."github.com/jonboulle/clockwork"]
    version = "v0.3.0"
    hash = "sha256-FFxY61QrDorg1U2ItCmjgwRksEUy/jsXLiKJviod1QM="
  [mod."github.com/klauspost/compress"]
    version = "v1.16.7"
    hash = "sha256-8miX/lnXyNLPSqhhn5BesLauaIAxETpQpWtr1cu2f+0="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.2.5"
    hash = "sha256-/M8CHNah2/EPr0va44r1Sx+3H6E+jN8bGFi5jQkLBrM="
  [mod."github.com/libdns/libdns"]
    version = "v0.2.1"
    hash = "sha256-bxEY0wYu4Um0t7sakLyMwMPDXfv2x07gjckKSyAypsc="
  [mod."github.com/manifoldco/promptui"]
    version = "v0.9.0"
    hash = "sha256-Fe2OPoyRExZejwtUBivKhfJAJW7o9b1eyYpgDlWQ1No="
  [mod."github.com/mastercactapus/proxyprotocol"]
    version = "v0.0.4"
    hash = "sha256-7wUqy9EDfR9XM4FRQ5KoqiueGCujGRtGPHYMnI/2fW0="
  [mod."github.com/mattermost/xml-roundtrip-validator"]
    version = "v0.1.0"
    hash = "sha256-b5lspAL/mbHzYJmgHOSztGCDvqwhiVyk/c6DX9aWcQg="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.19"
    hash = "sha256-wYQqGxeqV3Elkmn26Md8mKZ/viw598R4Ych3vtt72YE="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.4"
    hash = "sha256-uovu7OycdeZ2oYQ7FhVxLey5ZX3T0FzShaRldndyGvc="
  [mod."github.com/mgutz/ansi"]
    version = "v0.0.0-20200706080929-d51e80ef957d"
    hash = "sha256-RY6deYqJKpTTttr5tH2VW+PtuUIcieEq3Y6fGqRL0vk="
  [mod."github.com/mholt/acmez"]
    version = "v1.2.0"
    hash = "sha256-zfj14WFQr1/AO64gYsbFk4a4T0dsMEs+W3uIa9968/M="
  [mod."github.com/mholt/caddy-l4"]
    version = "v0.0.0-20230809152347-4e8aaac46581"
    hash = "sha256-qwjkb+77RtBbOBr7wkQ6mRH9D2rwvz0kOiIBmiyaVR8="
  [mod."github.com/micromdm/scep/v2"]
    version = "v2.1.0"
    hash = "sha256-vs0CBvUVXRh6n+XI7GlvdijNC9/Vec0LpywCCEivo0g="
  [mod."github.com/miekg/dns"]
    version = "v1.1.55"
    hash = "sha256-Jbii9veDSpqF7yIkdrzb/bEUM3wZG41mNEAYV3VEAJo="
  [mod."github.com/mitchellh/copystructure"]
    version = "v1.2.0"
    hash = "sha256-VR9cPZvyW62IHXgmMw8ee+hBDThzd2vftgPksQYR/Mc="
  [mod."github.com/mitchellh/go-ps"]
    version = "v1.0.0"
    hash = "sha256-HzxVHNLHZpnsBuPcub0G+9jjDcDOsxM/6wifbsxf7EY="
  [mod."github.com/mitchellh/reflectwalk"]
    version = "v1.0.2"
    hash = "sha256-VX9DPqChm7jPnyrA3RAYgxAFrAhj7TRKIWD/qR9Zr9s="
  [mod."github.com/onsi/ginkgo/v2"]
    version = "v2.11.0"
    hash = "sha256-WpG834pL9N89s/yh6ngRzHUcwmInZsYTUY56JjdxV4U="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.16.0"
    hash = "sha256-P/b4/8m1ztF0fCLSJ+eRXN74Bncx2vjOJx7nFl2QEg4="
  [mod."github.com/prometheus/client_model"]
    version = "v0.4.0"
    hash = "sha256-4P0sPWpxa69gGM6zm3dA06cH6twaeopq22VVDJjucHA="
  [mod."github.com/prometheus/common"]
    version = "v0.44.0"
    hash = "sha256-8n3gSWKDSJtGfOQgxsiCGyTnUjb5hvSxJi/hPcrE5Oo="
  [mod."github.com/prometheus/procfs"]
    version = "v0.11.1"
    hash = "sha256-yphZ7NZtYC/tb0HVag2T58SuN64Ial9sBo/TdCEQx6Q="
  [mod."github.com/quic-go/qpack"]
    version = "v0.4.0"
    hash = "sha256-QWIumzmHD94DlNp9G3AQf9QCtF+Kv0pShT1+FH7/I/c="
  [mod."github.com/quic-go/qtls-go1-20"]
    version = "v0.3.1"
    hash = "sha256-nmNXfgj/BR0p0C7tyG/fqAnQFC8fW1G8t/w5ziQiQ4c="
  [mod."github.com/quic-go/quic-go"]
    version = "v0.37.3"
    hash = "sha256-Ys/pRFNy/KoO2lok8k4+CZWY+/o1fYqtdWo8aXN/ztY="
  [mod."github.com/russellhaering/goxmldsig"]
    version = "v1.3.0"
    hash = "sha256-8mbTMDFhQW34AuKgniVoOKs4gcPf8wPNJQZUEHD4ISk="
  [mod."github.com/russross/blackfriday/v2"]
    version = "v2.1.0"
    hash = "sha256-R+84l1si8az5yDqd5CYcFrTyNZ1eSYlpXKq6nFt4OTQ="
  [mod."github.com/shopspring/decimal"]
    version = "v1.3.1"
    hash = "sha256-MA3RmMQKPrposbqXcHdvAJL50O1WsIe0EBd7rMSWPPA="
  [mod."github.com/shurcooL/sanitized_anchor_name"]
    version = "v1.0.0"
    hash = "sha256-DtFSzeLmD1fAl103ncgwab7Vv2F0aulsA+gbkq24ab8="
  [mod."github.com/skip2/go-qrcode"]
    version = "v0.0.0-20200617195104-da1b6568686e"
    hash = "sha256-ST9t4/b7WFXUb8wra4ZYVDNZJGrEykw8dkWhLrxp8F0="
  [mod."github.com/slackhq/nebula"]
    version = "v1.7.2"
    hash = "sha256-fYhR0dyaQPhJSGxSDPUw/UXsfI9E3zz21di0nzLnGW0="
  [mod."github.com/smallstep/certificates"]
    version = "v0.24.3-rc1"
    hash = "sha256-j3sALsceSIn9UdMUpC9B9+4YZBHHO48PcWmAMjTKoA4="
  [mod."github.com/smallstep/nosql"]
    version = "v0.6.0"
    hash = "sha256-cv+ZRZMWzmDSSzPQdWfvgfE0N1KVtuapYOKPeOzs/B0="
  [mod."github.com/smallstep/truststore"]
    version = "v0.12.1"
    hash = "sha256-Kboc+343ZeGFeCnYxeH2Wd04M2Gsk9CNMAMnA0keRxk="
  [mod."github.com/spf13/cast"]
    version = "v1.5.1"
    hash = "sha256-/tQNGGQv+Osp+2jepQaQe6GlncZbqdxzSR82FieiUBU="
  [mod."github.com/spf13/cobra"]
    version = "v1.7.0"
    hash = "sha256-bom9Zpnz8XPwx9IVF+GAodd3NVQ1dM1Uwxn8sy4Gmzs="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/stoewer/go-strcase"]
    version = "v1.3.0"
    hash = "sha256-X0ilcefeqVQ44B9WT6euCMcigs7oLFypOQaGI33kGr8="
  [mod."github.com/tailscale/tscert"]
    version = "v0.0.0-20230509043813-4e9cb4f2b4ad"
    hash = "sha256-7jfqO3vI2s7N+Gz9hmK3NDhP+GQi9uRV/mTLztSmtBk="
  [mod."github.com/things-go/go-socks5"]
    version = "v0.0.3"
    hash = "sha256-mKDxUSrpzfdUSdoFBGTRTPfXZ8HLd7wmMGeV8eRvtWc="
  [mod."github.com/urfave/cli"]
    version = "v1.22.14"
    hash = "sha256-lpNDP0bM02JWeUjCOXU8HwHk3FT5zB4gIOO/EvaxRao="
  [mod."github.com/zeebo/blake3"]
    version = "v0.2.3"
    hash = "sha256-ZepnzkvOyicTGL078O1F84q0TzBAouJlB5AMmfsiOIg="
  [mod."go.etcd.io/bbolt"]
    version = "v1.3.7"
    hash = "sha256-poZk8tPLDWwW95oCOkTJcQtEvOJTD9UXAZ2TqGJutwk="
  [mod."go.mozilla.org/pkcs7"]
    version = "v0.0.0-20210826202110-33d05740a352"
    hash = "sha256-x5OuHrnMWNfcLZCyQ6zaGm+ah8DMli2CCQg5z6qWgb8="
  [mod."go.step.sm/cli-utils"]
    version = "v0.8.0"
    hash = "sha256-6o5mUWfeju7GJDxfsrSlvMyL0/vHmj1l8bVuWfeOaYg="
  [mod."go.step.sm/crypto"]
    version = "v0.33.0"
    hash = "sha256-0e1WoAFHRIvHQD0Jx4UhU8aNyTeChxH9hkrwsCjYD14="
  [mod."go.step.sm/linkedca"]
    version = "v0.20.0"
    hash = "sha256-Epvs3PeUslMYVe+w3uy1FNW6qNMRsAeJESHgdKNurQo="
  [mod."go.uber.org/goleak"]
    version = "v1.2.1"
    hash = "sha256-APb7f9Qlnw7AESlPhMRJj2vSmbIyN4fO2KlOEfXLywc="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."go.uber.org/zap"]
    version = "v1.25.0"
    hash = "sha256-aU270ds5r37xtfFFDVrvjOTTOv1aZNd7ffvHZJB6VIQ="
  [mod."golang.org/x/crypto"]
    version = "v0.12.0"
    hash = "sha256-Wes72EA9ICTG8o0nEYWZk9xjpqlniorFeY6o26GExns="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20230801115018-d63ba01acd4b"
    hash = "sha256-c1Vwmar6gDUqWIcx7zcwQcZI/T44B1C9dy5Jiqddi2Y="
  [mod."golang.org/x/mod"]
    version = "v0.12.0"
    hash = "sha256-M/oXnzm7odpJdQzEnG6W0pNYtl0uhOM/l7qgfGVpU2M="
  [mod."golang.org/x/net"]
    version = "v0.14.0"
    hash = "sha256-QScKgO7lBWOsd0Y31wLRzFETv3tjqdB/eRQWW5q7aV4="
  [mod."golang.org/x/sync"]
    version = "v0.3.0"
    hash = "sha256-bCJKLvwExhYacH2ZrWlZ38lr1d6oNenNt2m1QqDCs0o="
  [mod."golang.org/x/sys"]
    version = "v0.11.0"
    hash = "sha256-g/LjhABK2c/u6v7M2aAIrHvZjmx/ikGHkef86775N38="
  [mod."golang.org/x/term"]
    version = "v0.11.0"
    hash = "sha256-muSv/d8Qpl+NXiOB01n6LeFEzC+hrlGviDdfu+6QdQ4="
  [mod."golang.org/x/text"]
    version = "v0.12.0"
    hash = "sha256-aNQaW3EgCK9ehpnBzIAkZX6TmiUU1S175YlJUH7P5Qg="
  [mod."golang.org/x/time"]
    version = "v0.3.0"
    hash = "sha256-/hmc9skIswMYbivxNS7R8A6vCTUF9k2/7tr/ACkcEaM="
  [mod."golang.org/x/tools"]
    version = "v0.11.1"
    hash = "sha256-jGHRdJzmlQucfSQrmi5Uq6xzAubJ6fKGydefeD+vP7s="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20230731193218-e0aa005b6bdf"
    hash = "sha256-J5jdWPiLpWSEVkEghxbQaCb1CG0HqodshHOr/7yw1x0="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20230731193218-e0aa005b6bdf"
    hash = "sha256-HyfjBmpZdolOTPdQhzoTkHsCProHohXQIu/Nat5pAbA="
  [mod."google.golang.org/grpc"]
    version = "v1.57.0"
    hash = "sha256-hP6alxFu+pcLI4gT3idzEMYNp+DbU3P4xhkpIqGCPXg="
  [mod."google.golang.org/protobuf"]
    version = "v1.31.0"
    hash = "sha256-UdIk+xRaMfdhVICvKRk1THe3R1VU+lWD8hqoW/y8jT0="
  [mod."gopkg.in/square/go-jose.v2"]
    version = "v2.6.0"
    hash = "sha256-GRzbqF2tkyZ8/XEDkGNxF7TxBxd3z3umy/zD6jqGNqw="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."howett.net/plist"]
    version = "v1.0.0"
    hash = "sha256-sySpZjk+EXYSv4cqtRiyVWOQ68W/SlrE/uyI4o/5CGY="
