#!/usr/bin/env bash
start_agent() {
  ssh-agent -a "$1" > /dev/null
  ssh-add
}

export SSH_AUTH_SOCK="${SSH_AUTH_SOCK:-${HOME}/.ssh/ssh_auth_sock}"

MESSAGE="$(LC_ALL=en_US.UTF-8 ssh-add -L 2>&1)"
if [[ "$MESSAGE" = 'Could not open a connection to your authentication agent.' ]] || \
  [[ "$MESSAGE" = 'Error connecting to agent: Connection refused' ]] || \
  [[ "$MESSAGE" = 'Error connecting to agent: No such file or directory' ]]; then
  rm -f "$SSH_AUTH_SOCK"
  start_agent "$SSH_AUTH_SOCK"
elif [ "$MESSAGE" = "The agent has no identities." ]; then
  ssh-add
fi

"$@"
