[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
user=root
environment=LANG="zh_CN.UTF-8",LC_ALL="zh_CN.UTF-8",DISPLAY=":99"

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:xvfb]
command=/usr/bin/Xvfb :99 -screen 0 "%(ENV_X_RESOLUTION)s" -ac
autorestart=true
priority=100
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=2
stdout_logfile=/var/log/supervisor/xvfb.log
stderr_logfile=/var/log/supervisor/xvfb.log

[program:openbox]
command=/usr/bin/openbox
environment=DISPLAY=":99",LANG="zh_CN.UTF-8",LC_ALL="zh_CN.UTF-8"
autorestart=true
priority=200
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=2
stdout_logfile=/var/log/supervisor/openbox.log
stderr_logfile=/var/log/supervisor/openbox.log

[program:x11vnc]
command=sh -c 'echo "%(ENV_VNC_PASSWORD)s" > /tmp/vnc-passwdfile; /usr/bin/x11vnc -display :99 -forever -shared -rfbport 5900 -passwdfile /tmp/vnc-passwdfile -xkb'
priority=300
autorestart=true
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=2
stdout_logfile=/var/log/supervisor/x11vnc.log

[program:novnc]
command=/opt/novnc/utils/novnc_proxy --vnc localhost:5900 --listen 6080
priority=400
autorestart=true
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=2
stdout_logfile=/var/log/supervisor/novnc.log
stderr_logfile=/var/log/supervisor/novnc.log

[program:x11check]
command=sh -c ' \
    timeout=60; \
    start_time=$SECONDS; \
    until xdpyinfo -display :99 >/dev/null 2>&1; do \
        if [ $(( $SECONDS - $start_time )) -gt $timeout ]; then \
            echo "X11 check timed out after $timeout seconds" >&2; \
            exit 1; \
        fi; \
        sleep 1; \
    done; \
    touch /root/.Xauthority; \
    supervisorctl start vdi'
priority=400
autorestart=false
startsecs=0
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=2
stdout_logfile=/var/log/supervisor/x11check.log
stderr_logfile=/var/log/supervisor/x11check.log

[program:vdi]
command=/opt/apps/com.cmss.saas.ecloudcomputer/files/ecloud-cloud-computer-application --no-sandbox --remote-debugging-port=9222 --remote-allow-origins=*
environment=DISPLAY=":99"
autorestart=false
priority=500
startsecs=5
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stdout_logfile=/var/log/supervisor/vdi.log

[include]
files = /etc/supervisor/conf.d/*.conf
