singleuser:
  image:
    name: jupyter/minimal-notebook
    tag: "2343e33dec46"
  profileList:
    - default: true
      description: To avoid too much bells and whistles
      display_name: Minimal Environment
    - description: "If you want the additional bells and whistles: Python, R, and Julia."
      display_name: Datascience Environment
      kubespawner_override:
        image: jupyter/datascience-notebook:2343e33dec46
    - description: "The Jupyter Stacks spark image!"
      display_name: Spark Environment
      kubespawner_override:
        image: jupyter/all-spark-notebook:2343e33dec46
    - description: "The ihaskell image!"
      display_name: Ihaskell Environment
      kubespawner_override:
        image: crosscompass/ihaskell-notebook:3c46e409a47b
    - description: Datascience Environment with Sample Notebooks
      display_name: Learning Data Science
      kubespawner_override:
        image: jupyter/datascience-notebook:2343e33dec46
        lifecycle_hooks:
          postStart:
            exec:
              command:
                - sh
                - "-c"
                - |
                  gitpuller https://github.com/data-8/materials-fa17 master materials-fa;
