# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rspool/ROOT/nixos";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "rspool/NIX/nix";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "rspool/VAR/var";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "rspool/HOME/home";
      fsType = "zfs";
    };

  fileSystems."/tmp" =
    { device = "rspool/TMP/tmp";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FDC4-3965";
      fsType = "vfat";
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
