# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "rpool/ROOT/nixos";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    {
      device = "rpool/NIX/nix";
      fsType = "zfs";
    };

  fileSystems."/var" =
    {
      device = "rpool/VAR/var";
      fsType = "zfs";
    };

  fileSystems."/home" =
    {
      device = "rpool/HOME/home";
      fsType = "zfs";
    };

  fileSystems."/tmp" =
    {
      device = "rpool/TMP/tmp";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/CCA9-80D9";
      fsType = "vfat";
    };

  swapDevices = [ ];
}
