# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "tank/ROOT/nixos";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "tank/NIX/nix";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "tank/VAR/var";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "tank/HOME/home";
      fsType = "zfs";
    };

  fileSystems."/tmp" =
    { device = "tank/TMP/tmp";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/43EA-463C";
      fsType = "vfat";
    };

  swapDevices = [ ];

}
