setup-info-locations:
  - "http://mirrors.tuna.tsinghua.edu.cn/stackage/stack-setup.yaml"
urls:
  latest-snapshot: http://mirrors.tuna.tsinghua.edu.cn/stackage/snapshots.json
allow-newer: true
nix:
  pure: false
ghc-options:
  "$everything": -haddock
