#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------


# The first parameter sets the step to change the volume by (and units to display)
# This may be in in % or dB (eg. 5% or 3dB)
STEP="${1:-5}"

#------------------------------------------------------------------------

volume() {
  pamixer --get-volume
}

#------------------------------------------------------------------------

case $BLOCK_BUTTON in
  3) pamixer --toggle-mute ;;  # right click, mute/unmute
  4) pamixer --increase $STEP ;; # scroll up, increase
  5) pamixer --decrease $STEP ;; # scroll down, decrease
esac

volume
