- name: Set variables for socket activation
  vars:
    tmp: "{{ without_socket_activation | default(ansible_facts['distribution'] == 'NixOS') }}"
  set_fact:
    without_socket_activation: "{{ tmp }}"
    caddy_config_url: "{{ caddy_config_url_without_socket_activation if tmp else caddy_config_url_with_socket_activation }}"

- name: Create a temporary directory for staging
  ansible.builtin.tempfile:
    state: directory
    suffix: _quadlet_staging
  register: staging_dir

- name: Set root directory
  set_fact:
    # Basename of directory is used as app name, so we append a name here
    root_dir: "{{ staging_dir.path }}/caddy"
    raw_template: "{{ lookup('template', 'caddy.quadlets.j2') }}"

- name: Ensure root directory exists
  file:
    path: "{{ root_dir }}"
    recurse: true
    state: directory

- name: Create individual files from stanzas
  ansible.builtin.copy:
    dest: "{{ root_dir }}/{{ file.split('\n')[0] | trim }}"
    content: "{{ file.split('\n')[1:] | join('\n') | trim }}"
    mode: '0644'
  loop: "{{ raw_template.split('---') | map('trim') | select() | list }}"
  loop_control:
    loop_var: file
    label: "File: {{ file.splitlines()[0] | default('unknown') | trim }}"

- name: Apply Podman Quadlet (Daemon Reload & Start)
  containers.podman.podman_quadlet:
    state: present
    src: "{{ root_dir }}"
  register: podman_quadlet

- name: Cleanup the temporary staging directory
  ansible.builtin.file:
    path: "{{ staging_dir.path }}"
    force: true
    state: absent

- name: Configure socket activation
  when: not without_socket_activation
  vars:
    templates:
      - src: caddy.socket.j2
        dest: /usr/local/lib/systemd/system/caddy.socket
  block:
    - name: Ensure configuration directories exist
      ansible.builtin.file:
        path: "{{ template.dest | dirname }}"
        state: directory
        mode: '0755'
      loop: "{{ templates }}"
      loop_control:
        loop_var: template

    - name: Copy Caddy configuration and systemd unit
      ansible.builtin.template:
        src: "{{ template.src }}"
        dest: "{{ template.dest }}"
        mode: "0644"
      loop: "{{ templates }}"
      loop_control:
        loop_var: template
      register: systemd_unit

    - name: Start/reload unit
      ansible.builtin.systemd:
        name: "{{ template.dest | basename }}"
        state: restarted
        daemon_reload: yes
        enabled: yes
      when: systemd_unit.changed or podman_quadlet.changed
      loop: "{{ templates }}"
      loop_control:
        loop_var: template
