- set_fact:
    tcp_forwarding_ports: "{{ edge_proxy_tcp_forwarding_ports }}"
    udp_forwarding_ports: "{{ edge_proxy_udp_forwarding_ports }}"
    resolvers: "{{ edge_proxy_resolvers }}"
    backend_ips: "{{ edge_proxy_backend_ip_addresses.split(',') }}"
    port_mappings: "{{ edge_proxy_port_mappings }}"

- name: Install and configure envoy
  when:
    - use_envoy
  block:
    - name: Add envoy gpg key
      when: ansible_facts['os_family'] == "Debian"
      ansible.builtin.apt_key:
        url: https://deb.dl.getenvoy.io/public/gpg.8115BA8E629CC074.key
        state: present

    - name: Set envoy ubuntu repo
      when: ansible_facts['distribution'] == "Ubuntu"
      set_fact:
        envoyproxy_repository:
          - "deb [arch=amd64] https://deb.dl.getenvoy.io/public/deb/ubuntu {{ ansible_facts['distribution_release'] }} stable"

    - name: Install envoy
      include_role:
        name: hugoprudente.envoyproxy

    - name: Copy templates to default directory
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0644"
      loop:
        - src: envoy.yaml.j2
          dest: /etc/envoy/envoy.yaml
      register: envoy_config

    - name: Start/reload Envoy Proxy
      service:
        name: envoyproxy
        state: restarted
        enabled: yes
        daemon_reload: yes
      when: envoy_config.changed
