# Our distro is too old, we want to install the latest podman
# - name: Installing podman
#   package:
#     name: "podman"
#     state: absent

- name: Install containers_common
  ansible.builtin.include_role:
    name: alvistack.containers_common

- name: Installing podman
  ansible.builtin.include_role:
    name: alvistack.podman
