- name: Install rclone
  include_role:
    role: stefangweichinger.ansible_rclone

- name: Check rclone installed
  shell: |
    command -v rclone
  register: check_rclone_installed

- name: Set rclone_executable fact
  ansible.builtin.set_fact:
    rclone_executable: "{{ check_rclone_installed.stdout | trim }}"

- name: Configure rclone
  vars:
    rclone_file_definitions:
      - src: rclone.service.j2
        dest: /usr/local/lib/systemd/system/rclone.service
  block:
    - name: Ensure configuration directories exist
      ansible.builtin.file:
        path: "{{ rclone_item.dest | dirname }}"
        state: directory
        mode: '0755'
      loop: "{{ rclone_file_definitions }}"
      loop_control:
        loop_var: rclone_item

    - name: Copy rclone configuration and systemd unit
      ansible.builtin.template:
        src: "{{ rclone_item.src }}"
        dest: "{{ rclone_item.dest }}"
        mode: "0644"
      loop: "{{ rclone_file_definitions }}"
      loop_control:
        loop_var: rclone_item
      register: rclone_unit

    - name: Start/reload rclone
      ansible.builtin.systemd:
        name: rclone
        state: restarted
        daemon_reload: yes
        enabled: yes
      when: rclone_unit.changed
