- name: Set base SSH private key path if not defined
  ansible.builtin.set_fact:
    force_sign: "{{ force_sign | default(False) }}"
    host_ssh_key_path: "{{ host_ssh_key_path | default('/etc/ssh/ssh_host_ed25519_key') }}"

- name: Derive Public Key and Certificate paths from the private key path
  ansible.builtin.set_fact:
    host_ssh_pub_key_path: "{{ host_ssh_key_path }}.pub"
    host_ssh_certificate_path: "{{ host_ssh_key_path }}-cert.pub"

- name: Verify the derived files exist on the target
  ansible.builtin.stat:
    path: "{{ file }}"
  register: ssh_files
  loop:
    - "{{ host_ssh_key_path }}"
    - "{{ host_ssh_pub_key_path }}"
  loop_control:
    loop_var: file

- name: Assert all SSH components are present
  ansible.builtin.assert:
    that:
      - file.stat.exists
    fail_msg: "Host key set to {{ host_ssh_key_path }}, but required SSH file missing: {{ file.file }}"
  loop: "{{ ssh_files.results }}"
  loop_control:
    loop_var: file

- name: Ensure the variable 'pkcs11_library_path' is defined
  ansible.builtin.assert:
    that:
      - pkcs11_library_path is defined
      - pkcs11_library_path | length > 0
    fail_msg: "The variable 'pkcs11_library_path' is missing or empty!"
    success_msg: "Variable 'pkcs11_library_path' is present."

- name: Check if the file path exists
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ pkcs11_library_path }}"
  register: file_status

- name: Assert that the file actually exists on the target
  delegate_to: localhost
  ansible.builtin.assert:
    that:
      - file_status.stat.exists
    fail_msg: "The file path '{{ pkcs11_library_path }}' does not exist."
    success_msg: "Confirmed: '{{ pkcs11_library_path }}' exists."

- name: Extract CA Pub Key for signing command
  delegate_to: localhost
  become: no
  shell: |
    ssh-keygen -D "{{ pkcs11_library_path }}" | grep "Digital Signature"
  register: local_ca_pub
  changed_when: false

- name: Create a temporary directory for staging
  delegate_to: localhost
  ansible.builtin.tempfile:
    state: directory
    suffix: _ssh_host_ca
  register: tmp_dir

- name: Check if host certificate exists
  stat:
    path: "{{ host_ssh_certificate_path }}"
  register: cert_file

- name: Extract Signing CA fingerprint from existing certificate
  shell: "ssh-keygen -L -f {{ host_ssh_certificate_path }} | grep 'Signing CA' | awk '{print $3}'"
  register: remote_ca_fingerprint
  when: cert_file.stat.exists
  changed_when: false

- name: Assert certificate non-existent if not force_sign
  ansible.builtin.assert:
    that:
      - (not cert_file.stat.exists) or (force_sign | bool)
    fail_msg: "Host key certificate exists but we are not force signing"

- name: Fetch the remote host public key
  fetch:
    src: "{{ host_ssh_pub_key_path }}"
    dest: "{{ tmp_dir.path }}/{{ inventory_hostname }}.pub"
    flat: yes

- name: Save CA pub key locally
  delegate_to: localhost
  become: no
  copy:
    content: "{{ local_ca_pub.stdout }}"
    dest: "{{ tmp_dir.path }}/ca.pub"
    mode: '0600'

- name: Execute signing command
  delegate_to: localhost
  become: no
  shell: |
    ssh-keygen -s "{{ tmp_dir.path }}/ca.pub" -D "{{ pkcs11_library_path }}" -I "{{ inventory_hostname }}" -h -n "{{ inventory_hostname }},{{ ansible_host }}" "{{ tmp_dir.path }}/{{ inventory_hostname }}.pub"

- name: "Ensure /etc/ssh/sshd_config.d directory exists"
  ansible.builtin.file:
    path: "/etc/ssh/sshd_config.d"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "Ensure main sshd_config includes the config directory"
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    line: "Include /etc/ssh/sshd_config.d/*.conf"
    insertbefore: "BOF"
    state: "present"
    validate: "/usr/sbin/sshd -t -f %s"
  register: "include_check"

- name: "Upload the signed certificate"
  ansible.builtin.copy:
    src: "{{ tmp_dir.path }}/{{ inventory_hostname }}-cert.pub"
    dest: "{{ host_ssh_certificate_path }}"
    owner: "root"
    group: "root"
    mode: "0644"
  register: "cert_upload"

- name: "Create dedicated SSH CA configuration file"
  ansible.builtin.copy:
    dest: "/etc/ssh/sshd_config.d/host-ca.conf"
    content: "HostCertificate {{ host_ssh_certificate_path }}\n"
    owner: "root"
    group: "root"
    mode: "0600"
    validate: "/usr/sbin/sshd -t -f %s"
  register: "ca_config"

- name: "Reload SSH if any configuration changed"
  ansible.builtin.service:
    name: "ssh"
    state: "reloaded"
  when: "include_check.changed or cert_upload.changed or ca_config.changed"

- name: Add Host CA to local known_hosts
  delegate_to: localhost
  become: no
  ansible.builtin.lineinfile:
    path: "~/.ssh/known_hosts"
    line: "@cert-authority * {{ local_ca_pub.stdout }}"
    create: yes
    mode: '0600'
    state: present

- name: Remove the temporary directory
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ tmp_dir.path }}"
    state: absent
