- name: Create a temporary directory for staging
  ansible.builtin.tempfile:
    state: directory
    suffix: _quadlet_staging
  register: staging_dir

- name: Set variables
  set_fact:
    # Basename of directory is used as app name, so we append a name here
    root_dir: "{{ staging_dir.path }}/wstunnel@"
    wstunnel_dir: "/etc/wstunnel"
    raw_template: "{{ lookup('template', 'wstunnel@.quadlets.j2') }}"

- name: Ensure directories exists
  file:
    path: "{{ dir }}"
    recurse: true
    state: directory
  loop:
    - "{{ root_dir }}"
    - "{{ wstunnel_dir }}"
  loop_control:
    loop_var: dir

- name: Create individual files from stanzas
  ansible.builtin.copy:
    dest: "{{ root_dir }}/{{ file.split('\n')[0] | trim }}"
    content: "{{ file.split('\n')[1:] | join('\n') | trim }}"
    mode: '0644'
  loop: "{{ raw_template.split('---') | map('trim') | select() | list }}"
  loop_control:
    loop_var: file
    label: "File: {{ file.splitlines()[0] | default('unknown') | trim }}"

- name: Create instance files
  ansible.builtin.copy:
    dest: "{{ wstunnel_dir }}/{{ idx }}.env"
    content: "WSTUNNEL_COMMAND={{ command | string | trim | quote }}"
    mode: '0644'
  loop: "{{ wstunnel_instances }}"
  loop_control:
    loop_var: command
    index_var: idx

- name: Apply Podman Quadlet
  containers.podman.podman_quadlet:
    state: present
    src: "{{ root_dir }}"
  register: podman_quadlet

- name: Start/reload service
  ansible.builtin.systemd:
    name: "wstunnel@{{ idx }}"
    state: restarted
    enabled: yes
  when: podman_quadlet.changed
  loop: "{{ wstunnel_instances }}"
  loop_control:
    loop_var: command
    index_var: idx

- name: Cleanup the temporary staging directory
  ansible.builtin.file:
    path: "{{ staging_dir.path }}"
    force: true
    state: absent
