{
  ...
}:
{
  prefs.machine.type = "laptop";
  prefs.sing-box.enable = true;
  prefs.tuned.extraExtremePowersaveRules = {
    # Automatically generated by powertop2tuned tool
    # sudo powertop --html=htmlfile.html
    # powertop2tuned --input htmlfile.html --output . --force
    audio = {
      # Energieverwaltung für Audiocodec aktivieren
      timeout = 1;
    };

    sysfs = {
      # AutoSuspend für USB-Gerät N-KEY Device [ASUSTeK Computer Inc.]
      "/sys/bus/usb/devices/3-9/power/control" = "auto";

      # Laufzeit-Energieverwaltung für PCI-Gerät Intel Corporation Platform Monitoring Technology
      "/sys/bus/pci/devices/0000:00:0a.0/power/control" = "auto";

      # Laufzeit-Energieverwaltung für PCI-Gerät Sandisk Corp WD SN560/SN740/SN770/SN5000 NVMe SSD
      "/sys/bus/pci/devices/10000:e1:00.0/power/control" = "auto";

      # Laufzeit-Energieverwaltung für PCI-Gerät Intel Corporation Volume Management Device NVMe RAID Controller
      "/sys/bus/pci/devices/0000:00:0e.0/power/control" = "auto";

      # Laufzeit-Energieverwaltung für PCI-Gerät Sandisk Corp WD SN560/SN740/SN770/SN5000 NVMe SSD
      "/sys/bus/pci/devices/10000:e2:00.0/power/control" = "auto";

      # Laufzeit-Energieverwaltung für PCI-Gerät Intel Corporation RST VMD Managed Controller
      "/sys/bus/pci/devices/0000:00:06.0/power/control" = "auto";

      # Laufzeit-Energieverwaltung für PCI-Gerät Realtek Semiconductor Co., Ltd. RTL8125 2.5GbE Controller
      "/sys/bus/pci/devices/0000:2c:00.0/power/control" = "auto";

      # Laufzeit-Energieverwaltung für PCI-Gerät Intel Corporation 12th Gen Core Processor Host Bridge/DRAM Registers
      "/sys/bus/pci/devices/0000:00:00.0/power/control" = "auto";

      # Wake-On-LAN-Status für Gerät eno2
      "/sys/class/net/eno2/device/power/wakeup" = "disabled";

      # Wake-On-LAN-Status für Gerät wlan0
      "/sys/class/net/wlan0/device/power/wakeup" = "disabled";

      # Wake status for USB device usb3
      "/sys/bus/usb/devices/usb3/power/wakeup" = "disabled";

      # Wake status for USB device usb1
      "/sys/bus/usb/devices/usb1/power/wakeup" = "disabled";

      # Wake status for USB device usb4
      "/sys/bus/usb/devices/usb4/power/wakeup" = "disabled";

      # Wake status for USB device 3-10
      "/sys/bus/usb/devices/3-10/power/wakeup" = "disabled";

      # Wake status for USB device usb2
      "/sys/bus/usb/devices/usb2/power/wakeup" = "disabled";
    };
  };
}
