[[language]]
name = "nix"
language-servers = ["nixd", "nil"]
formatter = { command = "nixfmt" }
formatter.args = ["-"]
auto-format = true

name = "yaml"
formatter = { command = 'prettier', args = ["--parser", "yaml"] }
auto-format = true
