- hosts: localhost
  gather_facts: false
  tasks:
    - name: Install cockroachdb
      block:
        - name: Decrypt secrets
          template:
            src: "{{ item }}"
            dest: "{{ artifacts_dir }}"
            decrypt: true
          with_fileglob:
            - "files/cockroachdb.yaml*"
        - name: Install
          community.kubernetes.helm:
            name: coachroachdb
            chart_repo_url: "https://charts.cockroachdb.com/"
            chart_version: "5.0.6"
            chart_ref: cockroachdb
            release_namespace: "{{ default_namespace }}"
            kubeconfig: "{{ kubeconfig }}"
            create_namespace: true
            values_files: "{{ lookup('fileglob', '{{ artifacts_dir }}/cockroachdb.yaml*') }}"
