[theme]
theme = "solarized-dark"
[icons]
icons = "awesome4"

[[block]]
block = "focused_window"
[block.format]
full = "$title.str(max_w:75)|"
short = "$title.str(max_w:20,rot_interval:0.5)|"

[[block]]
block = "disk_space"
alert_unit = "GB"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(prefix:M)/$swap_total.eng(prefix:M)($swap_used_percents.eng(w:2)) "

[[block]]
block = "cpu"

[[block]]
block = "load"

[[block]]
block = "sound"

[[block]]
block = "battery"
missing_format = ""
full_format = ""

[[block]]
block = "pomodoro"
notify_cmd = "notify-send $msg"
blocking_cmd = false

[[block]]
block = "time"
interval = 5
format = "$timestamp.datetime(f:'%a %d/%m %R')"
