section: screens
	aol:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none
		switchCornerSize = 0
	wae:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none
		switchCornerSize = 0
	pak:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none
		switchCornerSize = 0
end

section: aliases
end

section: links
	aol:
		right = wae
	wae:
		right = pak
		left = aol
	pak:
		left = wae
end

section: options
	protocol = synergy
	relativeMouseMoves = true
	win32KeepForeground = true
	defaultLockToScreenState = false
	disableLockToScreen = false
	clipboardSharing = true
	clipboardSharingSize = 3072
	switchCorners = none
	switchCornerSize = 0
	keystroke(Control+Alt+Shift+s) = switchToNextScreen
	keystroke(Control+Alt+Shift+Up) = switchInDirection(up)
	keystroke(Control+Alt+Shift+Down) = switchInDirection(down)
	keystroke(Control+Alt+Shift+Left) = switchInDirection(left)
	keystroke(Control+Alt+Shift+Right) = switchInDirection(right)
	keystroke(Control+Alt+Shift+q) = keystroke(Control+Alt+Shift+l,*)
end
