name: Build container images

on:
  workflow_dispatch: {}

jobs:
  build-container-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository:
          - "bookwyrm-social/bookwyrm"

    steps:
      - name: Set upstream information
        id: upstream
        run: |
          repository=${{ matrix.repository }}
          name="$(awk -F / '{print $2}' <<< "$repository")"
          directory="$name"
          echo "::set-output name=name::$name"
          echo "::set-output name=directory::$directory"
          echo "::set-output name=repository::$repository"

      - name: Checkout ${{ steps.upstream.outputs.name }} from ${{ steps.upstream.outputs.repository }}
        uses: actions/checkout@v2
        with:
          repository: ${{ steps.upstream.outputs.repository }}
          path: ${{ steps.upstream.outputs.directory }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Get docker environment
        id: env
        working-directory: ${{ steps.upstream.outputs.directory }}
        run: |
          set -xeuo pipefail
          [[ -z "${DOCKER_HUB_USERNAME:-}" ]] && DOCKER_HUB_USERNAME="$(awk -F / '{print $1}' <<< "$GITHUB_REPOSITORY")"
          PACKAGE_NAME=${{ steps.upstream.outputs.name }}
          DOCKER_TAG="$(git log --format="%H" -n 1)"
          DOCKER_HUB_URL="$DOCKER_HUB_USERNAME/$PACKAGE_NAME"
          DOCKER_IMAGE="$DOCKER_HUB_URL:$DOCKER_TAG"
          DOCKER_IMAGE_CACHE="$DOCKER_HUB_URL:cache"
          DOCKER_IMAGE_LATEST="$DOCKER_HUB_URL:latest"
          echo "::set-output name=PACKAGE_NAME::$PACKAGE_NAME"
          echo "::set-output name=DOCKER_HUB_USERNAME::$DOCKER_HUB_USERNAME"
          echo "::set-output name=DOCKER_IMAGE::$DOCKER_IMAGE"
          echo "::set-output name=DOCKER_IMAGE_LATEST::$DOCKER_IMAGE_LATEST"
          echo "::set-output name=DOCKER_IMAGE_CACHE::$DOCKER_IMAGE_CACHE"
          echo "::set-output name=DOCKER_TAGS::$DOCKER_IMAGE,$DOCKER_IMAGE_LATEST"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ steps.env.outputs.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ steps.upstream.outputs.directory }}
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.env.outputs.DOCKER_TAGS }}
          cache-from: ${{ steps.env.outputs.DOCKER_IMAGE_CACHE }}
          cache-to: ${{ steps.env.outputs.DOCKER_IMAGE_CACHE }}
